name: DeepStoragePlus
version: 1.2.8
main: me.darkolythe.deepstorageplus.DeepStoragePlus
api-version: 1.13

commands:
  deepstorageplus:
    usage: /<command>
    aliases: [dsp]
    description: the base dsp command
    permission: deepstorageplus.command
    permission-message: You do not have permission!

permissions:
  deepstorageplus.create:
    description: Allows the user to create a DSU
    default: op